(assert! (address (bitdiddle ben) (slumerville (ridge road) 10)))
(assert! (job (bitdiddle ben) (computer wizard)))
(assert! (salary (bitdiddle ben) 60000))
(assert! (address (hacker alyssa p) (cambridge (mass ave) 78)))
(assert! (job (hacker alyssa p) (computer programmer)))
(assert! (salary (hacker alyssa p) 40000))
(assert! (supervisor (hacker alyssa p) (bitdiddle ben)))
(assert! (address (fect cy d) (cambridge (ames street) 3)))
(assert! (job (fect cy d) (computer programmer)))
(assert! (salary (fect cy d) 35000))
(assert! (supervisor (fect cy d) (bitdiddle ben)))
(assert! (address (tweakit lem e) (boston (bay state road) 22)))
(assert! (job (tweakit lem e) (computer technician)))
(assert! (salary (tweakit lem e) 25000))
(assert! (supervisor (tweakit lem e) (bitdiddle ben)))
(assert! (address (reasoner louis) (slumerville (pine tree road) 80)))
(assert! (job (reasoner louis) (computer programmer trainee)))
(assert! (salary (reasoner louis) 30000))
(assert! (supervisor (reasoner louis) (hacker alyssa p)))
(assert! (supervisor (bitdiddle ben) (warbucks oliver)))
(assert! (address (warbucks oliver) (swellesley (top heap road))))
(assert! (job (warbucks oliver) (administration big wheel)))
(assert! (salary (warbucks oliver) 150000))
(assert! (address (scrooge eben) (weston (shady lane) 10)))
(assert! (job (scrooge eben) (accounting chief accountant)))
(assert! (salary (scrooge eben) 75000))
(assert! (supervisor (scrooge eben) (warbucks oliver)))
(assert! (address (cratchet robert) (allston (n harvard street) 16)))
(assert! (job (cratchet robert) (accounting scrivener)))
(assert! (salary (cratchet robert) 18000))
(assert! (supervisor (cratchet robert) (scrooge eben)))
(assert! (address (aull dewitt) (slumerville (onion square) 5)))
(assert! (job (aull dewitt) (administration secretary)))
(assert! (salary (aull dewitt) 25000))
(assert! (supervisor (aull dewitt) (warbucks oliver)))
(assert! (can-do-job (computer wizard) (computer programmer)))
(assert! (can-do-job (computer wizard) (computer technician)))
(assert! (can-do-job (computer programmer) (computer programmer trainee)))
(assert! (can-do-job (administration secretary) (administration big wheel)))
(assert! (rule (same ?x ?x)))
(assert! (meeting accounting (monday |9am|)))
(assert! (meeting administration (monday |10am|)))
(assert! (meeting computer (wednesday |3pm|)))
(assert! (meeting administration (friday |1pm|)))
(assert! (meeting whole-company (wednesday |4pm|)))
(assert! (rule (lives-near ?person-1 ?person-2) (and (address ?person-1 (?town . ?rest-1)) (address ?person-2 (?town . ?rest-2)) (not (same ?person-1 ?person-2)))))
