;;; a)
;;; Query-input: 
(and (supervisor ?name  (Bitdiddle Ben))
     (address ?name ?where))

;;; Query-output: 
(and (supervisor (tweakit lem e) (bitdiddle ben))
     (address (tweakit lem e) (boston (bay state road) 22)))
(and (supervisor (fect cy d) (bitdiddle ben))
     (address (fect cy d) (cambridge (ames street) 3)))
(and (supervisor (hacker alyssa p) (bitdiddle ben))
     (address (hacker alyssa p) (cambridge (mass ave) 78)))


;;;b)
;;; Query-input: 
(and (salary (Bitdiddle Ben) ?ben-salary)
     (and (salary ?name ?amount)
          (lisp-value < ?amount ?ben-salary)))

;;; Query-output: 
(and (salary (bitdiddle ben) 60000)
     (and (salary (aull dewitt) 25000)
          (lisp-value < 25000 60000)))
(and (salary (bitdiddle ben) 60000)
     (and (salary (cratchet robert) 18000)
          (lisp-value < 18000 60000)))
(and (salary (bitdiddle ben) 60000)
     (and (salary (reasoner louis) 30000)
          (lisp-value < 30000 60000)))
(and (salary (bitdiddle ben) 60000)
     (and (salary (tweakit lem e) 25000)
          (lisp-value < 25000 60000)))
(and (salary (bitdiddle ben) 60000)
      (and (salary (fect cy d) 35000)
           (lisp-value < 35000 60000)))
(and (salary (bitdiddle ben) 60000)
     (and (salary (hacker alyssa p) 40000)
          (lisp-value < 40000 60000)))


;;;c)
;;; Query-input: 
(and (supervisor ?name ?sup)
     (not (job ?sup (compoter . ?)))
     (job ?sup ?job))

;;; Query-output: 
(and (supervisor (aull dewitt) (warbucks oliver))
     (not (job (warbucks oliver) (compoter . ?)))
     (job (warbucks oliver) (administration big wheel)))
(and (supervisor (cratchet robert) (scrooge eben))
     (not (job (scrooge eben) (compoter . ?)))
     (job (scrooge eben) (accounting chief accountant)))
(and (supervisor (scrooge eben) (warbucks oliver))
     (not (job (warbucks oliver) (compoter . ?)))
     (job (warbucks oliver) (administration big wheel)))
(and (supervisor (bitdiddle ben) (warbucks oliver))
     (not (job (warbucks oliver) (compoter . ?)))
     (job (warbucks oliver) (administration big wheel)))
(and (supervisor (reasoner louis) (hacker alyssa p))
     (not (job (hacker alyssa p) (compoter . ?)))
     (job (hacker alyssa p) (computer programmer)))
(and (supervisor (tweakit lem e) (bitdiddle ben))
     (not (job (bitdiddle ben) (compoter . ?)))
     (job (bitdiddle ben) (computer wizard)))
(and (supervisor (fect cy d) (bitdiddle ben))
     (not (job (bitdiddle ben) (compoter . ?)))
     (job (bitdiddle ben) (computer wizard)))
(and (supervisor (hacker alyssa p) (bitdiddle ben))
     (not (job (bitdiddle ben) (compoter . ?)))
     (job (bitdiddle ben) (computer wizard)))